// Auto-generated by export_supported_ranges_ts.sh
// Do not edit manually; regenerate from API.

export type SupportedRange = {
  min_start: number;
  max_end: number;
};

export const SUPPORTED_RANGES_GENERATED_AT = "2026-04-16T02:44:59Z";

export const SUPPORTED_RANGES: Record<string, SupportedRange> = {
  "1": {
    "max_end": 248600000,
    "min_start": 750000
  },
  "10": {
    "max_end": 133600000,
    "min_start": 0
  },
  "11": {
    "max_end": 134850000,
    "min_start": 250000
  },
  "12": {
    "max_end": 133100000,
    "min_start": 0
  },
  "13": {
    "max_end": 114350000,
    "min_start": 16250000
  },
  "14": {
    "max_end": 106850000,
    "min_start": 16500000
  },
  "15": {
    "max_end": 101850000,
    "min_start": 17750000
  },
  "16": {
    "max_end": 90100000,
    "min_start": 0
  },
  "17": {
    "max_end": 83100000,
    "min_start": 500000
  },
  "18": {
    "max_end": 80100000,
    "min_start": 0
  },
  "19": {
    "max_end": 58600000,
    "min_start": 250000
  },
  "2": {
    "max_end": 242100000,
    "min_start": 0
  },
  "20": {
    "max_end": 64350000,
    "min_start": 250000
  },
  "21": {
    "max_end": 46600000,
    "min_start": 9500000
  },
  "22": {
    "max_end": 50600000,
    "min_start": 13250000
  },
  "3": {
    "max_end": 198100000,
    "min_start": 0
  },
  "4": {
    "max_end": 190100000,
    "min_start": 0
  },
  "5": {
    "max_end": 181350000,
    "min_start": 0
  },
  "6": {
    "max_end": 170600000,
    "min_start": 250000
  },
  "7": {
    "max_end": 159100000,
    "min_start": 250000
  },
  "8": {
    "max_end": 145100000,
    "min_start": 250000
  },
  "9": {
    "max_end": 138350000,
    "min_start": 0
  },
  "X": {
    "max_end": 155850000,
    "min_start": 250000
  }
} as const;

export const SUPPORTED_RANGE_LIST: Array<{ chrom: string } & SupportedRange> = [
  {
    "chrom": "1",
    "min_start": 750000,
    "max_end": 248600000
  },
  {
    "chrom": "2",
    "min_start": 0,
    "max_end": 242100000
  },
  {
    "chrom": "3",
    "min_start": 0,
    "max_end": 198100000
  },
  {
    "chrom": "4",
    "min_start": 0,
    "max_end": 190100000
  },
  {
    "chrom": "5",
    "min_start": 0,
    "max_end": 181350000
  },
  {
    "chrom": "6",
    "min_start": 250000,
    "max_end": 170600000
  },
  {
    "chrom": "7",
    "min_start": 250000,
    "max_end": 159100000
  },
  {
    "chrom": "8",
    "min_start": 250000,
    "max_end": 145100000
  },
  {
    "chrom": "9",
    "min_start": 0,
    "max_end": 138350000
  },
  {
    "chrom": "10",
    "min_start": 0,
    "max_end": 133600000
  },
  {
    "chrom": "11",
    "min_start": 250000,
    "max_end": 134850000
  },
  {
    "chrom": "12",
    "min_start": 0,
    "max_end": 133100000
  },
  {
    "chrom": "13",
    "min_start": 16250000,
    "max_end": 114350000
  },
  {
    "chrom": "14",
    "min_start": 16500000,
    "max_end": 106850000
  },
  {
    "chrom": "15",
    "min_start": 17750000,
    "max_end": 101850000
  },
  {
    "chrom": "16",
    "min_start": 0,
    "max_end": 90100000
  },
  {
    "chrom": "17",
    "min_start": 500000,
    "max_end": 83100000
  },
  {
    "chrom": "18",
    "min_start": 0,
    "max_end": 80100000
  },
  {
    "chrom": "19",
    "min_start": 250000,
    "max_end": 58600000
  },
  {
    "chrom": "20",
    "min_start": 250000,
    "max_end": 64350000
  },
  {
    "chrom": "21",
    "min_start": 9500000,
    "max_end": 46600000
  },
  {
    "chrom": "22",
    "min_start": 13250000,
    "max_end": 50600000
  },
  {
    "chrom": "X",
    "min_start": 250000,
    "max_end": 155850000
  }
] as const;

export function getSupportedRange(chrom: string): SupportedRange | undefined {
  const key = String(chrom).replace(/^chr/i, "");
  return SUPPORTED_RANGES[key];
}
